use actual pqkeys for testing

diff --git a/testing/lean-spec-tests/Makefile b/testing/lean-spec-tests/Makefile
--- a/testing/lean-spec-tests/Makefile
+++ b/testing/lean-spec-tests/Makefile
@@ -1,5 +1,7 @@
 EXTRACT_DIR = fixtures
 REPO_URL = https://github.com/ReamLabs/lean-spec-tests.git
+KEYS_DIR = fixtures/keys/prod_scheme
+KEYS_URL = https://github.com/leanEthereum/leansig-test-keys/releases/download/leanSpec-bbbbf62/prod_scheme.tar.gz
 
 .PHONY: all clean test
 
@@ -14,12 +16,22 @@ $(EXTRACT_DIR):
 		echo "Fixtures downloaded successfully."; \
 	fi
 
-test: $(EXTRACT_DIR)
+$(KEYS_DIR):
+	@if [ -d $(KEYS_DIR) ]; then \
+		echo "$(KEYS_DIR) already exists. Skipping download."; \
+	else \
+		echo "Downloading test keys..."; \
+		mkdir -p fixtures/keys; \
+		curl -sL $(KEYS_URL) | tar xz -C fixtures/keys || { echo "Key download failed."; exit 1; }; \
+		echo "Test keys downloaded successfully."; \
+	fi
+
+test: $(EXTRACT_DIR) $(KEYS_DIR)
 	@echo "Running lean-spec tests..."
 	@cargo test --release --features lean-spec-tests
 	@echo "Tests complete."
 
 clean:
-	@echo "Cleaning up downloaded fixtures..."
+	@echo "Cleaning up downloaded fixtures and keys..."
 	@rm -rf $(EXTRACT_DIR)
 	@echo "Clean up complete."
